#!/bin/bash
ODMDATA=0x6090000
SYSBOOTFILE=p2771-0000/extlinux.conf;
DTB_FILE=tegra186-tx2i-cti-ASG002-revF+.dtb;
TBCDTB_FILE=$DTB_FILE;
ext_target_board=cti-tx2i-asg002-00;

source "${LDK_DIR}/cti-tx2i.conf.common";
